create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete restrict,
  customer_id uuid references public.customers(id) on delete set null,
  order_number bigint generated by default as identity,
  channel text not null default 'web',
  fulfillment_type text not null default 'pickup',
  status text not null default 'pending_payment',
  payment_status text not null default 'pending',
  customer_name text not null,
  customer_phone text,
  customer_email text,
  delivery_address_snapshot jsonb,
  subtotal_amount numeric(10, 2) not null default 0,
  discount_amount numeric(10, 2) not null default 0,
  delivery_fee numeric(10, 2) not null default 0,
  tax_amount numeric(10, 2) not null default 0,
  total_amount numeric(10, 2) not null default 0,
  currency text not null default 'MXN',
  notes text,
  placed_at timestamptz not null default now(),
  confirmed_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_channel_check check (channel in ('web', 'mobile', 'admin')),
  constraint orders_fulfillment_type_check check (fulfillment_type in ('pickup', 'delivery')),
  constraint orders_status_check check (status in ('pending_payment', 'confirmed', 'in_preparation', 'ready', 'completed', 'cancelled')),
  constraint orders_payment_status_check check (payment_status in ('pending', 'paid', 'failed', 'refunded')),
  constraint orders_amounts_non_negative check (
    subtotal_amount >= 0
    and discount_amount >= 0
    and delivery_fee >= 0
    and tax_amount >= 0
    and total_amount >= 0
  )
);

create unique index if not exists idx_orders_tenant_id_order_number
  on public.orders(tenant_id, order_number);

create index if not exists idx_orders_tenant_id
  on public.orders(tenant_id);

create index if not exists idx_orders_branch_id
  on public.orders(branch_id);

create index if not exists idx_orders_customer_id
  on public.orders(customer_id);

create index if not exists idx_orders_status_placed_at
  on public.orders(status, placed_at desc);

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name_snapshot text not null,
  category_name_snapshot text,
  unit_price_snapshot numeric(10, 2) not null,
  quantity integer not null,
  line_total numeric(10, 2) not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_items_quantity_positive check (quantity > 0),
  constraint order_items_prices_non_negative check (unit_price_snapshot >= 0 and line_total >= 0)
);

create index if not exists idx_order_items_order_id
  on public.order_items(order_id);

create index if not exists idx_order_items_product_id
  on public.order_items(product_id);

drop trigger if exists set_order_items_updated_at on public.order_items;
create trigger set_order_items_updated_at
before update on public.order_items
for each row
execute function public.set_updated_at();

create table if not exists public.order_item_modifiers (
  id uuid primary key default gen_random_uuid(),
  order_item_id uuid not null references public.order_items(id) on delete cascade,
  modifier_group_name_snapshot text not null,
  modifier_option_name_snapshot text not null,
  price_snapshot numeric(10, 2) not null default 0,
  created_at timestamptz not null default now(),
  constraint order_item_modifiers_price_non_negative check (price_snapshot >= 0)
);

create index if not exists idx_order_item_modifiers_order_item_id
  on public.order_item_modifiers(order_item_id);

create table if not exists public.order_status_history (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  from_status text,
  to_status text not null,
  changed_by_profile_id uuid references public.profiles(id) on delete set null,
  source text not null default 'system',
  created_at timestamptz not null default now(),
  constraint order_status_history_source_check check (source in ('system', 'admin', 'customer', 'kitchen'))
);

create index if not exists idx_order_status_history_order_id
  on public.order_status_history(order_id, created_at desc);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  provider text,
  provider_payment_id text,
  status text not null default 'pending',
  amount numeric(10, 2) not null,
  currency text not null default 'MXN',
  paid_at timestamptz,
  raw_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payments_status_check check (status in ('pending', 'paid', 'failed', 'refunded')),
  constraint payments_amount_non_negative check (amount >= 0)
);

create index if not exists idx_payments_order_id
  on public.payments(order_id);

drop trigger if exists set_payments_updated_at on public.payments;
create trigger set_payments_updated_at
before update on public.payments
for each row
execute function public.set_updated_at();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_item_modifiers enable row level security;
alter table public.order_status_history enable row level security;
alter table public.payments enable row level security;

drop policy if exists orders_select on public.orders;
create policy orders_select
on public.orders
for select
to authenticated
using (
  public.has_tenant_access(tenant_id)
  or (
    customer_id is not null
    and exists (
      select 1
      from public.customers c
      where c.id = customer_id
        and c.profile_id = public.current_profile_id()
    )
  )
);

drop policy if exists orders_manage on public.orders;
create policy orders_manage
on public.orders
for all
to authenticated
using (public.has_branch_access(branch_id))
with check (public.has_branch_access(branch_id));

drop policy if exists order_items_select on public.order_items;
create policy order_items_select
on public.order_items
for select
to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = order_id
      and (
        public.has_tenant_access(o.tenant_id)
        or (
          o.customer_id is not null
          and exists (
            select 1
            from public.customers c
            where c.id = o.customer_id
              and c.profile_id = public.current_profile_id()
          )
        )
      )
  )
);

drop policy if exists order_items_manage on public.order_items;
create policy order_items_manage
on public.order_items
for all
to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = order_id
      and public.has_branch_access(o.branch_id)
  )
)
with check (
  exists (
    select 1
    from public.orders o
    where o.id = order_id
      and public.has_branch_access(o.branch_id)
  )
);

drop policy if exists order_item_modifiers_select on public.order_item_modifiers;
create policy order_item_modifiers_select
on public.order_item_modifiers
for select
to authenticated
using (
  exists (
    select 1
    from public.order_items oi
    join public.orders o on o.id = oi.order_id
    where oi.id = order_item_id
      and (
        public.has_tenant_access(o.tenant_id)
        or (
          o.customer_id is not null
          and exists (
            select 1
            from public.customers c
            where c.id = o.customer_id
              and c.profile_id = public.current_profile_id()
          )
        )
      )
  )
);

drop policy if exists order_item_modifiers_manage on public.order_item_modifiers;
create policy order_item_modifiers_manage
on public.order_item_modifiers
for all
to authenticated
using (
  exists (
    select 1
    from public.order_items oi
    join public.orders o on o.id = oi.order_id
    where oi.id = order_item_id
      and public.has_branch_access(o.branch_id)
  )
)
with check (
  exists (
    select 1
    from public.order_items oi
    join public.orders o on o.id = oi.order_id
    where oi.id = order_item_id
      and public.has_branch_access(o.branch_id)
  )
);

drop policy if exists order_status_history_select on public.order_status_history;
create policy order_status_history_select
on public.order_status_history
for select
to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = order_id
      and (
        public.has_tenant_access(o.tenant_id)
        or (
          o.customer_id is not null
          and exists (
            select 1
            from public.customers c
            where c.id = o.customer_id
              and c.profile_id = public.current_profile_id()
          )
        )
      )
  )
);

drop policy if exists order_status_history_manage on public.order_status_history;
create policy order_status_history_manage
on public.order_status_history
for all
to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = order_id
      and public.has_branch_access(o.branch_id)
  )
)
with check (
  exists (
    select 1
    from public.orders o
    where o.id = order_id
      and public.has_branch_access(o.branch_id)
  )
);

drop policy if exists payments_select on public.payments;
create policy payments_select
on public.payments
for select
to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = order_id
      and (
        public.has_tenant_access(o.tenant_id)
        or (
          o.customer_id is not null
          and exists (
            select 1
            from public.customers c
            where c.id = o.customer_id
              and c.profile_id = public.current_profile_id()
          )
        )
      )
  )
);

drop policy if exists payments_manage on public.payments;
create policy payments_manage
on public.payments
for all
to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = order_id
      and public.has_branch_access(o.branch_id)
  )
)
with check (
  exists (
    select 1
    from public.orders o
    where o.id = order_id
      and public.has_branch_access(o.branch_id)
  )
);
